"""Narrative Markdown export report generator."""

import logging
from datetime import datetime

from ..core.device import get_device_info
from ..utils.formatters import format_bytes

logger = logging.getLogger(__name__)


def _period_label(start_date: str, end_date: str, days_tracked: int) -> str:
    if start_date == end_date:
        return "Day"
    if start_date and start_date.endswith("-01-01") and days_tracked > 300:
        return "Year"
    if start_date and start_date.endswith("-01") and days_tracked <= 31:
        return "Month"
    if days_tracked <= 7:
        return "Week"
    return "Period"


def generate_markdown_report(data: dict) -> str:
    _device_id, _os_type, hostname = get_device_info()

    start = data.get("start_date", "")
    end = data.get("end_date", "")
    days = data.get("days_tracked", 0)
    label = _period_label(start, end, days)

    total_bytes = data.get("total_bytes", 0)
    sent = data.get("total_sent", 0)
    received = data.get("total_received", 0)
    daily_avg = data.get("daily_avg", 0)
    peak_speed = data.get("peak_speed", 0)

    personality = data.get("personality", {})
    comparisons = data.get("fun_comparisons", {})
    breakdown = data.get("monthly_breakdown", [])
    cost = data.get("cost", {})

    now = datetime.now().strftime("%B %d, %Y at %I:%M %p")

    lines = []

    lines.append(f"# Your {label} in Internet")
    lines.append("")
    lines.append(f"**Hostname:** {hostname}")
    lines.append("")
    lines.append(f"**Period:** {start} — {end}")
    lines.append("")
    lines.append(
        f"{personality.get('icon', '')} **{personality.get('type', 'User')}** — "
        f"{personality.get('desc', '')}"
    )
    lines.append("")
    lines.append("---")
    lines.append("")

    lines.append("## By the Numbers")
    lines.append("")
    lines.append(f"- **Total Data:** {format_bytes(total_bytes)}")
    lines.append(f"- **Days Tracked:** {days}")
    lines.append(f"- **Daily Average:** {format_bytes(daily_avg)}")
    lines.append(f"- **Peak Speed:** {format_bytes(peak_speed)}/s")
    lines.append("")

    lines.append("## Upload vs Download")
    lines.append("")
    lines.append(f"- **Upload:** {format_bytes(sent)}")
    lines.append(f"- **Download:** {format_bytes(received)}")
    lines.append("")

    lines.append("## Monthly Breakdown")
    lines.append("")
    if breakdown:
        lines.append("| Month | Sent | Received | Total |")
        lines.append("|-------|------|----------|-------|")
        for m in breakdown:
            lines.append(
                f"| {m['month']} | {format_bytes(m['bytes_sent'])} | "
                f"{format_bytes(m['bytes_received'])} | {format_bytes(m['total_bytes'])} |"
            )
    else:
        lines.append("_No monthly data available._")
    lines.append("")

    lines.append("## Fun Facts")
    lines.append("")
    lines.append(
        f"- **{comparisons.get('dvd_equivalent', 0)} DVDs** — "
        f"That's how many DVDs your data would fill!"
    )
    lines.append(
        f"- **{comparisons.get('hd_movies', 0)} HD Movies** — "
        f"Streaming equivalent in HD quality."
    )
    lines.append(
        f"- **{comparisons.get('web_pages', 0):,} Web Pages** — "
        f"Number of web pages your data could load."
    )
    lines.append(
        f"- **{comparisons.get('coffee_cups', 0)} Cups of Coffee** — "
        f"Data center energy equivalent cups of coffee."
    )
    lines.append("")

    lines.append("## Cost Summary")
    lines.append("")
    total_cost = cost.get("total", {})
    upload_cost = cost.get("upload", {})
    download_cost = cost.get("download", {})
    lines.append(f"- **Total Cost:** {total_cost.get('cost_formatted', 'N/A')}")
    lines.append(f"- **Upload Cost:** {upload_cost.get('cost_formatted', 'N/A')}")
    lines.append(f"- **Download Cost:** {download_cost.get('cost_formatted', 'N/A')}")
    lines.append(
        f"- **Rate:** ₹{cost.get('cost_per_gb', 0):.2f} per GB"
    )
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(f"*Generated by PacketBuddy on {now}*")
    lines.append("")

    return "\n".join(lines)
